dev:
  deploy:
    parameters:
      stack_name: monolith-app
      resolve_s3: true
      s3_prefix: monolith-app
      region: us-east-1
      capabilities: CAPABILITY_IAM
      disable_rollback: false
      image_repositories: []
version: 0.1
